spring:
  application:
    name: flight-service
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616
#  autoconfigure:
#    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#    exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration


server:
  port: 8080
  error:
    include-message: always